from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 760)
        MainWindow.setMinimumSize(QtCore.QSize(300, 760))
        MainWindow.setMaximumSize(QtCore.QSize(300, 760))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_welcome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_welcome.setGeometry(QtCore.QRect(70, 10, 160, 25))
        self.label_welcome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_welcome.setObjectName("label_welcome")
        self.button_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(90, 40, 113, 35))
        self.button_enter.setObjectName("button_enter")
        self.label_select_type = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_select_type.setGeometry(QtCore.QRect(80, 100, 151, 21))
        self.label_select_type.setObjectName("label_select_type")
        self.dropdown_list = QtWidgets.QComboBox(parent=self.centralwidget)
        self.dropdown_list.setGeometry(QtCore.QRect(93, 130, 130, 35))
        self.dropdown_list.setObjectName("dropdown_list")
        self.button_select = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_select.setGeometry(QtCore.QRect(78, 160, 141, 35))
        self.button_select.setObjectName("button_select")
        self.frame_option1 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_option1.setGeometry(QtCore.QRect(20, 200, 120, 170))
        self.frame_option1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_option1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_option1.setObjectName("frame_option1")
        self.radioButton_option1 = QtWidgets.QRadioButton(parent=self.frame_option1)
        self.radioButton_option1.setGeometry(QtCore.QRect(-1, 90, 111, 31))
        self.radioButton_option1.setText("")
        self.radioButton_option1.setObjectName("radioButton_option1")
        self.dropdown_quantity1 = QtWidgets.QComboBox(parent=self.frame_option1)
        self.dropdown_quantity1.setGeometry(QtCore.QRect(10, 140, 60, 30))
        self.dropdown_quantity1.setObjectName("dropdown_quantity1")
        self.label_price1 = QtWidgets.QLabel(parent=self.frame_option1)
        self.label_price1.setGeometry(QtCore.QRect(10, 118, 80, 20))
        self.label_price1.setText("")
        self.label_price1.setObjectName("label_price1")
        self.frame_option2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_option2.setGeometry(QtCore.QRect(150, 200, 120, 170))
        self.frame_option2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_option2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_option2.setObjectName("frame_option2")
        self.radioButton_option2 = QtWidgets.QRadioButton(parent=self.frame_option2)
        self.radioButton_option2.setGeometry(QtCore.QRect(10, 90, 100, 20))
        self.radioButton_option2.setText("")
        self.radioButton_option2.setObjectName("radioButton_option2")
        self.dropdown_quantity2 = QtWidgets.QComboBox(parent=self.frame_option2)
        self.dropdown_quantity2.setGeometry(QtCore.QRect(10, 140, 60, 30))
        self.dropdown_quantity2.setObjectName("dropdown_quantity2")
        self.label_price2 = QtWidgets.QLabel(parent=self.frame_option2)
        self.label_price2.setGeometry(QtCore.QRect(10, 118, 80, 20))
        self.label_price2.setText("")
        self.label_price2.setObjectName("label_price2")
        self.frame_option3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_option3.setGeometry(QtCore.QRect(20, 410, 120, 170))
        self.frame_option3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_option3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_option3.setObjectName("frame_option3")
        self.radioButton_option3 = QtWidgets.QRadioButton(parent=self.frame_option3)
        self.radioButton_option3.setGeometry(QtCore.QRect(10, 90, 100, 20))
        self.radioButton_option3.setText("")
        self.radioButton_option3.setObjectName("radioButton_option3")
        self.dropdown_quantity3 = QtWidgets.QComboBox(parent=self.frame_option3)
        self.dropdown_quantity3.setGeometry(QtCore.QRect(10, 140, 60, 30))
        self.dropdown_quantity3.setObjectName("dropdown_quantity3")
        self.label_price3 = QtWidgets.QLabel(parent=self.frame_option3)
        self.label_price3.setGeometry(QtCore.QRect(10, 118, 80, 20))
        self.label_price3.setText("")
        self.label_price3.setObjectName("label_price3")
        self.frame_option4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_option4.setGeometry(QtCore.QRect(150, 410, 120, 170))
        self.frame_option4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_option4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_option4.setObjectName("frame_option4")
        self.radioButton_option4 = QtWidgets.QRadioButton(parent=self.frame_option4)
        self.radioButton_option4.setGeometry(QtCore.QRect(10, 90, 100, 20))
        self.radioButton_option4.setText("")
        self.radioButton_option4.setObjectName("radioButton_option4")
        self.dropdown_quantity4 = QtWidgets.QComboBox(parent=self.frame_option4)
        self.dropdown_quantity4.setGeometry(QtCore.QRect(10, 140, 60, 30))
        self.dropdown_quantity4.setObjectName("dropdown_quantity4")
        self.label_price4 = QtWidgets.QLabel(parent=self.frame_option4)
        self.label_price4.setGeometry(QtCore.QRect(10, 118, 80, 20))
        self.label_price4.setText("")
        self.label_price4.setObjectName("label_price4")
        self.button_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_add.setGeometry(QtCore.QRect(10, 600, 100, 35))
        self.button_add.setObjectName("button_add")
        self.label_pretax_total = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pretax_total.setGeometry(QtCore.QRect(170, 600, 100, 35))
        self.label_pretax_total.setText("")
        self.label_pretax_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_pretax_total.setObjectName("label_pretax_total")
        self.button_checkout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_checkout.setGeometry(QtCore.QRect(170, 640, 113, 35))
        self.button_checkout.setObjectName("button_checkout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_welcome.setText(_translate("MainWindow", "Welcome to V.S. Grocery"))
        self.button_enter.setText(_translate("MainWindow", "Enter"))
        self.label_select_type.setText(_translate("MainWindow", "Select a Grocery Type"))
        self.button_select.setText(_translate("MainWindow", "Select"))
        self.button_add.setText(_translate("MainWindow", "Add to Cart"))
        self.button_checkout.setText(_translate("MainWindow", "Checkout"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
