# Form implementation generated from reading ui file 'gui2.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(300, 760)
        self.label_receipt_items = QtWidgets.QLabel(parent=SecondWindow)
        self.label_receipt_items.setGeometry(QtCore.QRect(10, 150, 161, 220))
        self.label_receipt_items.setText("")
        self.label_receipt_items.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_receipt_items.setObjectName("label_receipt_items")
        self.label_item_prices = QtWidgets.QLabel(parent=SecondWindow)
        self.label_item_prices.setGeometry(QtCore.QRect(199, 150, 90, 220))
        self.label_item_prices.setText("")
        self.label_item_prices.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTop|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.label_item_prices.setObjectName("label_item_prices")
        self.label_checkout = QtWidgets.QLabel(parent=SecondWindow)
        self.label_checkout.setGeometry(QtCore.QRect(70, 40, 141, 25))
        self.label_checkout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_checkout.setObjectName("label_checkout")
        self.button_return2shop = QtWidgets.QPushButton(parent=SecondWindow)
        self.button_return2shop.setGeometry(QtCore.QRect(10, 90, 130, 35))
        self.button_return2shop.setObjectName("button_return2shop")
        self.button_confirm_checkout = QtWidgets.QPushButton(parent=SecondWindow)
        self.button_confirm_checkout.setGeometry(QtCore.QRect(160, 90, 130, 35))
        self.button_confirm_checkout.setObjectName("button_confirm_checkout")
        self.label_pretax_total = QtWidgets.QLabel(parent=SecondWindow)
        self.label_pretax_total.setGeometry(QtCore.QRect(169, 360, 121, 20))
        self.label_pretax_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pretax_total.setObjectName("label_pretax_total")
        self.label_tax = QtWidgets.QLabel(parent=SecondWindow)
        self.label_tax.setGeometry(QtCore.QRect(190, 380, 100, 20))
        self.label_tax.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_tax.setObjectName("label_tax")
        self.label_total = QtWidgets.QLabel(parent=SecondWindow)
        self.label_total.setGeometry(QtCore.QRect(190, 420, 100, 20))
        self.label_total.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_total.setObjectName("label_total")
        self.frame1 = QtWidgets.QFrame(parent=SecondWindow)
        self.frame1.setGeometry(QtCore.QRect(10, 470, 281, 181))
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame1.setObjectName("frame1")
        self.label_cash_card = QtWidgets.QLabel(parent=self.frame1)
        self.label_cash_card.setGeometry(QtCore.QRect(20, 50, 171, 30))
        self.label_cash_card.setObjectName("label_cash_card")
        self.input_cash_card = QtWidgets.QLineEdit(parent=self.frame1)
        self.input_cash_card.setGeometry(QtCore.QRect(10, 90, 140, 27))
        self.input_cash_card.setText("")
        self.input_cash_card.setObjectName("input_cash_card")
        self.button_pay = QtWidgets.QPushButton(parent=self.frame1)
        self.button_pay.setGeometry(QtCore.QRect(170, 90, 110, 35))
        self.button_pay.setObjectName("button_pay")
        self.radioButton_cash = QtWidgets.QRadioButton(parent=self.frame1)
        self.radioButton_cash.setGeometry(QtCore.QRect(10, 10, 100, 35))
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.radioButton_card = QtWidgets.QRadioButton(parent=self.frame1)
        self.radioButton_card.setGeometry(QtCore.QRect(90, 10, 100, 35))
        self.radioButton_card.setObjectName("radioButton_card")
        self.button_submit = QtWidgets.QPushButton(parent=self.frame1)
        self.button_submit.setGeometry(QtCore.QRect(160, 10, 113, 35))
        self.button_submit.setObjectName("button_submit")
        self.label_thankyou_error = QtWidgets.QLabel(parent=SecondWindow)
        self.label_thankyou_error.setGeometry(QtCore.QRect(30, 670, 221, 41))
        self.label_thankyou_error.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_thankyou_error.setWordWrap(True)
        self.label_thankyou_error.setObjectName("label_thankyou_error")

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Dialog"))
        self.label_checkout.setText(_translate("SecondWindow", "Ready to Checkout?"))
        self.button_return2shop.setText(_translate("SecondWindow", "Return to Shop"))
        self.button_confirm_checkout.setText(_translate("SecondWindow", "Checkout"))
        self.label_pretax_total.setText(_translate("SecondWindow", "pretax total"))
        self.label_tax.setText(_translate("SecondWindow", "tax @ 7%"))
        self.label_total.setText(_translate("SecondWindow", "Total"))
        self.label_cash_card.setText(_translate("SecondWindow", "Enter 16-digit Card Number"))
        self.button_pay.setText(_translate("SecondWindow", "Pay"))
        self.radioButton_cash.setText(_translate("SecondWindow", "Cash"))
        self.radioButton_card.setText(_translate("SecondWindow", "Card"))
        self.button_submit.setText(_translate("SecondWindow", "Submit"))
        self.label_thankyou_error.setText(_translate("SecondWindow", "Thank you for Shopping at V.S. Groceries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QDialog()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec())
